# Generated by Django 4.1.4 on 2023-02-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('no', models.IntegerField()),
            ],
        ),
    ]
